<pre class="metadata">
Title: Quantitative awesomeness
Shortname: spec-template
Status: LS
URL: https://jcbhmr.github.io/spec-template/
TR: https://jcbhmr.github.io/spec-template/
Repository: https://github.com/jcbhmr/spec-template jcbhmr/spec-template
Issue Tracking: GitHub https://github.com/jcbhmr/spec-template/issues
Issue Tracker Template: https://github.com/jcbhmr/spec-template/issues/{0}
Editor: Jacob Hummer, jcbhmr@outlook.com, https://jcbhmr.me/
Markup Shorthands: markdown yes
Abstract: Tellus integer feugiat scelerisque varius. Elementum integer enim neque volutpat. Placerat vestibulum lectus mauris ultrices.
</pre>

<pre class="include">path: intro.bs</pre>
