on:
  push:
    branches: [main]
    paths: [src/**, .github/workflows/deploy.yml]
jobs:
  deploy-github-pages:
    concurrency:
      group: deploy-github-pages
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          runCmd: mkdir -vp dist && bikeshed spec src/index.bs dist/index.html
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - id: deployment
        uses: actions/deploy-pages@v1
