on:
  push:
    branches: [main]
    paths: [src/**, .github/workflows/Publish spec.yml, scripts/**]
permissions: read-all|write-all
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  Publish_spec_to_GitHub_Pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pipx install bikeshed && bikeshed update
          scripts/build.sh
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - id: deployment
        uses: actions/deploy-pages@v1
